#!/usr/bin/env python

# This script accepts two arguments:
#
# 1. The pages sql file containing a SQL dump of the wikipedia pages table
# 2. The file to write the page titles out too
#
# The output file will be in the following format
#
# page_id, page_title
# page_id, page_title
# page_id, page_title
# ...
#
# We will be ignoring all pages not in the 0 namespace. This is the 'Main'
# namespace containing all actual information and should cut down on things by
# quite a bit
#
# See here http://www.mediawiki.org/wiki/Manual:Namespace#Built-in_namespaces


