#!/usr/bin/env python

# This script accepts three arguments:
#
# 1. The pages sql file containing a SQL dump of the wikipedia pages table
# 2. The page titles file containg all page titles
# 3. The file to write the page links graph too
#
# The output file will be in the following format
#
# page_id, linked_to_page_id linked_to_page_id ...
# page_id, linked_to_page_id linked_to_page_id ...
# page_id, linked_to_page_id linked_to_page_id ...
# page_id, linked_to_page_id linked_to_page_id ...
# ...
#
# We will be ignoring all pages that don't have an associated title in the
# passed page titles file
